Repository MrZabbah/rotom-net, pull requests merged in 2022-02, with the labels that each got.

#3 Team generator branch
  RotomNet/src/main/java/es/trident/rotomnet/controller/TeamGeneratorController.java
  RotomNet/src/main/java/es/trident/rotomnet/model/Team.java
  RotomNet/src/main/java/es/trident/rotomnet/service/NoSuchElementExceptionControllerAdvice.java
  RotomNet/src/main/java/es/trident/rotomnet/service/PokemonRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/service/PokemonService.java
  RotomNet/src/main/java/es/trident/rotomnet/service/TeamRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/service/TeamService.java
  RotomNet/src/main/resources/static/css/teamGenerated.css
  RotomNet/src/main/resources/static/css/teamGenerator.css
  RotomNet/src/main/resources/static/index.html
  RotomNet/src/main/resources/templates/teamCreated.html
  RotomNet/src/main/resources/templates/teamDisplay.html
  RotomNet/src/main/resources/templates/teamGeneratorForm.html
  RotomNet/src/main/resources/templates/teamList.html
Labels: bug, enhancement

#5 ARREGLO PROYECTO: Fix pokedex impl
  RotomNet/pom.xml
  RotomNet/src/main/java/es/trident/rotomnet/controller/CardBoardController.java
  RotomNet/src/main/java/es/trident/rotomnet/controller/TeamGeneratorController.java
  RotomNet/src/main/java/es/trident/rotomnet/model/Pokemon.java
  RotomNet/src/main/java/es/trident/rotomnet/model/PokemonCard.java
  RotomNet/src/main/java/es/trident/rotomnet/model/RotomCard.java
  RotomNet/src/main/java/es/trident/rotomnet/model/User.java
  RotomNet/src/main/java/es/trident/rotomnet/model/UserRotomCard.java
  RotomNet/src/main/java/es/trident/rotomnet/model/UserRotomCardId.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/PokemonRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/RotomCardRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/UserRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/UserRotomCardRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/service/PokemonService.java
  RotomNet/src/main/resources/application.properties
  RotomNet/src/main/resources/static/css/cardBoard.css
  RotomNet/src/main/resources/static/index.html
  RotomNet/src/main/resources/templates/NoOwnerCard.html
  RotomNet/src/main/resources/templates/card.html
  RotomNet/src/main/resources/templates/cardBoard.html
  RotomNet/src/main/resources/templates/deckCard.html
  RotomNet/src/main/resources/templates/pokedex.html
  RotomNet/src/main/resources/templates/pokedexCard.html
Labels: duplicate, enhancement

#9 index.html
  RotomNet/src/main/java/es/trident/rotomnet/controller/CardBoardController.java
  RotomNet/src/main/java/es/trident/rotomnet/service/TeamService.java
  RotomNet/src/main/resources/static/css/index.css
  RotomNet/src/main/resources/templates/header.html
  RotomNet/src/main/resources/templates/index.html
  RotomNet/src/main/resources/templates/teamCreated.html
Labels: enhancement

#10 Restricciones para evitar Usernames duplicados
  RotomNet/src/main/java/es/trident/rotomnet/controller/UserController.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/UserRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/service/UserService.java
  RotomNet/src/main/resources/static/css/modify.css
  RotomNet/src/main/resources/static/css/register.css
  RotomNet/src/main/resources/templates/modify.html
  RotomNet/src/main/resources/templates/register.html
  RotomNet/src/main/resources/templates/users.html
Labels: enhancement

#12 User team branch
  RotomNet/src/main/java/es/trident/rotomnet/controller/TeamGeneratorController.java
  RotomNet/src/main/java/es/trident/rotomnet/model/Team.java
  RotomNet/src/main/java/es/trident/rotomnet/model/User.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/TeamRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/UserRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/service/DatabaseManagementService.java
  RotomNet/src/main/java/es/trident/rotomnet/service/PokemonService.java
  RotomNet/src/main/java/es/trident/rotomnet/service/TeamService.java
  RotomNet/src/main/java/es/trident/rotomnet/service/UserService.java
  RotomNet/src/main/resources/templates/header.html
  RotomNet/src/main/resources/templates/teamCreated.html
  RotomNet/src/main/resources/templates/teamDisplay.html
  RotomNet/src/main/resources/templates/teamList.html
Labels: enhancement

#13 Merge: Combate Front-end + Selección Usuarios
  RotomNet/src/main/java/es/trident/rotomnet/controller/CardBoardController.java
  RotomNet/src/main/java/es/trident/rotomnet/controller/MainController.java
  RotomNet/src/main/java/es/trident/rotomnet/controller/UserController.java
  RotomNet/src/main/java/es/trident/rotomnet/service/UserService.java
  RotomNet/src/main/resources/static/css/battle.css
  RotomNet/src/main/resources/static/css/teamGenerator.css
  RotomNet/src/main/resources/static/css/teamList.css
  RotomNet/src/main/resources/static/css/users.css
  RotomNet/src/main/resources/templates/aux_users.html
  RotomNet/src/main/resources/templates/battle.html
  RotomNet/src/main/resources/templates/header.html
  RotomNet/src/main/resources/templates/teamList.html
Labels: enhancement

#14 Back End combate
  RotomNet/pom.xml
  RotomNet/src/main/java/es/trident/rotomnet/controller/BattleController.java
  RotomNet/src/main/java/es/trident/rotomnet/model/UserRotomCard.java
  RotomNet/src/main/java/es/trident/rotomnet/model/util/UserRotomCardId.java
  RotomNet/src/main/java/es/trident/rotomnet/repository/UserRotomCardRepository.java
  RotomNet/src/main/java/es/trident/rotomnet/service/BattleService.java
  RotomNet/src/main/java/es/trident/rotomnet/service/PokemonService.java
Labels: enhancement
